### ISSUE TITLE
Implement `acquiesce()`

### ISSUE THREAD

**Issue by jackgene** [propensive/parasite#18]
Per [the cancellation section of the README](https://github.com/propensive/parasite?tab=readme-ov-file#cancelation), checking for cancellation is done by calling `acquiesce()`.

However, the function does not appear to be implemented anywhere, as demonstrated [here](https://github.com/jackgene/easyracer/blob/40318bdd2af65f8c682a11e5409be8f9629adf20/scala-soundness/src/main/scala/EasyRacerClient.scala#L113).

Could I be missing something? For now, using [Thread.interrupted()](https://github.com/jackgene/easyracer/blob/40318bdd2af65f8c682a11e5409be8f9629adf20/scala-soundness/src/main/scala/EasyRacerClient.scala#L114) seems to work.

**Comment by propensive** [comment]
Sorry, this was a mistake in the documentation. I had renamed `acquiesce` to `relent`, but forgot to change the documentation.

But I've just spent the last couple of hours fixing that specific issue, and correcting several other issues with the text, as well as fixing a couple of longstanding issues in the code. So code and documentation should be in sync, at least for the parts of the library that are currently documented.

Something to be well aware of is that test coverage is unfortunately still insufficient, and needs a lot of work before relying on Parasite for anything important.
